# Generated by Django 4.2.23 on 2026-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('player1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('player2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('player3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('player4', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('player1MovedPiece', models.CharField(max_length=2)),
                ('player2MovedPiece', models.CharField(max_length=2)),
                ('player3MovedPiece', models.CharField(max_length=2)),
                ('player4MovedPiece', models.CharField(max_length=2)),
                ('player1DieNumber', models.IntegerField()),
                ('player2DieNumber', models.IntegerField()),
                ('player3DieNumber', models.IntegerField()),
                ('player4DieNumber', models.IntegerField()),
            ],
        ),
    ]
