# Generated by Django 4.2.23 on 2026-02-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='name',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player1DieNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player1MovedPiece',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player2DieNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player2MovedPiece',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player3DieNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player3MovedPiece',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player4DieNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='player4MovedPiece',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
